name: Package Application with Pyinstaller

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      run: |
        git clone https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git --single-branch --branch ${GITHUB_REF##*/} code
    - name: Install system requirements
      run: |
        sudo apt-get install libasound2-dev zip
    - name: Install python requirements
      run: |
        cd code
        pip3 install -r requirements.txt
    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: code

    - uses: actions/upload-artifact@v2
      with:
        name: name-of-artifact
        path: src/dist/windows
