name: Build executable

on: [push, pull_request]

jobs:
  Windows-Build:

    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        python -m pip install -r build_requirements.txt
        python -m pip uninstall enum34 -y
    - name: Make Executable
      run: |
        pyinstaller -F --add-data "devices;devices" -n havomi main.py
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
          name: Windows-Binary
          path: dist/havomi.exe
