name: Compile Diagram
on:
  push:
    branches:
      - main

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Compile
        run: |
          npm install mermaid.cli
          mmdc -i structure.mmd -o diagram.svg
          mmdc -i structure.mmd -o diagram.png
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
            name: diagram
            path: diagram.png
